In [1]:
import torch
torch.__version__

'2.4.0+cu121'

In [3]:
import torch
if torch.cuda.is_available():
    print("GPU is available")
else:
    print("GPU is not available")

GPU is available


Introduction to Tensors

In [2]:
scaler = torch.tensor(7)

In [3]:
# scaler
scaler.ndim
# get int from tensor
scaler.item()

7

In [4]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [5]:
vector.size(), vector.ndim

(torch.Size([2]), 1)

In [6]:
# MATRIX
MATRIX = torch.tensor([[2,3], [4,5]])
MATRIX

tensor([[2, 3],
        [4, 5]])

In [7]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [8]:
TENSOR.ndim

3

Random Tensors

In [9]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8988, 0.8010, 0.4867, 0.0631],
        [0.2806, 0.8828, 0.2719, 0.6315],
        [0.8434, 0.6088, 0.9582, 0.6003]])

Zero and Ones

In [10]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [11]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [12]:
zeros.dtype

torch.float32

In [13]:
a=torch.zeros([2,4,4])

In [14]:
a[1]

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Create a range of tensors and tensors like

In [15]:
# tensort.range()
even_num = torch.arange(start=0, end=10, step=2)
even_num

tensor([0, 2, 4, 6, 8])

In [16]:
# tensor.zeros_like()
like_even_num = torch.zeros_like(input=even_num)
like_even_num

tensor([0, 0, 0, 0, 0])

Tensor data types

In [17]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device='cuda', # what device is your tensor on cuda or cpu
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.], device='cuda:0')

In [18]:
float_32_tensor.dtype

torch.float32

In [19]:
float_16_tesor = float_32_tensor.type(torch.float16)
float_16_tesor.dtype

torch.float16

In [20]:
# create tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2572, 0.6723, 0.7891, 0.4298],
        [0.2995, 0.4169, 0.0561, 0.6326],
        [0.5649, 0.6632, 0.3927, 0.2489]])

In [21]:
# Find out details about some tensor
print(f'Datatype of tensor:     {some_tensor.dtype}')
print(f'Shape of tensor:        {some_tensor.shape}')
print(f'Device where tensor on: {some_tensor.shape}')

Datatype of tensor:     torch.float32
Shape of tensor:        torch.Size([3, 4])
Device where tensor on: torch.Size([3, 4])


Manipulating Tensors (tensor operations)

Tensor operation include:
* Addition
* Subtraction
* Multiplication
* Division
* Matrix Multiplication
  

In [22]:
tensor = torch.tensor([3,4,5])
tensor + 10

tensor([13, 14, 15])

In [23]:
tensor * 10

tensor([30, 40, 50])

In [24]:
tensor - 10

tensor([-7, -6, -5])

we have two ways for matrix multiplication:
* Element-wise
* two Matrix  (dot product)

In [25]:
# element-wise
print(tensor * tensor)

tensor([ 9, 16, 25])


In [26]:
# matrix multiplication
torch.matmul(tensor, tensor)

tensor(50)

Max, Min and Mean

In [27]:
x = torch.arange(1,20)
x.max(), torch.max(x)

(tensor(19), tensor(19))

In [28]:
# input dtype should be either floating point or complex dtypes for calculating mean
x.type(torch.float32).mean()

tensor(10.)

Find the positional min and max

In [29]:
x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19])

In [30]:
x.argmin(), x.argmax()

(tensor(0), tensor(18))

Reshaping, stacking

In [31]:
import torch
x = torch.arange(0.,5.)
x, x.shape

(tensor([0., 1., 2., 3., 4.]), torch.Size([5]))

In [32]:
x.reshape(5,1)

tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.]])

In [33]:
# add extra dimension
x.reshape(1,5)

tensor([[0., 1., 2., 3., 4.]])

In [34]:
z = x.view(5,1)
z

tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.]])

In [35]:
# the view of a tensor shares the same memory as orginal so changing it effect 
z[0,0] = 5
z, x

(tensor([[5.],
         [1.],
         [2.],
         [3.],
         [4.]]),
 tensor([5., 1., 2., 3., 4.]))

squeezing and unsqueezing

In [36]:
# Returns a tensor with all specified dimensions of input of size 1 removed.
x_squeezed = torch.zeros(1,9)
x_squeezed.shape

torch.Size([1, 9])

In [37]:
# torch.unsqueeze() - adds a single dimension to a target tensort at specific dim
print(f"Previous target: \n{x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"Previous target: \n{x_unsqueezed}")
print(f"Previous shape: {x_unsqueezed.shape}")

Previous target: 
tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0.]])
Previous shape: torch.Size([1, 9])
Previous target: 
tensor([[[0., 0., 0., 0., 0., 0., 0., 0., 0.]]])
Previous shape: torch.Size([1, 1, 9])


In [38]:
# torch permute change the dimensions order 
x_orginal = torch.randn(size=(224,224,3)) # 
x_permute = x_orginal.permute(2, 0, 1) # new order [color_channel, height, width]

print(f'Orginal shape: {x_orginal.shape}')
print(f'New shape    : {x_orginal.shape}')

Orginal shape: torch.Size([224, 224, 3])
New shape    : torch.Size([224, 224, 3])


Numpy In Pytorch

In [41]:
# numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # pytorch default datatype for numpy is float64
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [45]:
# tensor to numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [43]:

tensor

tensor([1., 1., 1., 1., 1., 1., 1.])