In [1]:
import torch
torch.__version__


Introduction to Tensors

In [3]:
scaler = torch.tensor(7)

In [4]:
# scaler
scaler.ndim
# get int from tensor
scaler.item()

7

In [5]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.size(), vector.ndim

(torch.Size([2]), 1)

In [7]:
# MATRIX
MATRIX = torch.tensor([[2,3], [4,5]])
MATRIX

tensor([[2, 3],
        [4, 5]])

In [8]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [9]:
TENSOR.ndim

3

Random Tensors

In [10]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3061, 0.6056, 0.3458, 0.6446],
        [0.4049, 0.3481, 0.4796, 0.5777],
        [0.2590, 0.0424, 0.1797, 0.2534]])

Zero and Ones

In [11]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [12]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [13]:
zeros.dtype

torch.float32

In [14]:
a=torch.zeros([2,4,4])

In [15]:
a[1]

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Create a range of tensors and tensors like

In [16]:
# tensort.range()
even_num = torch.arange(start=0, end=10, step=2)
even_num

tensor([0, 2, 4, 6, 8])

In [17]:
# tensor.zeros_like()
like_even_num = torch.zeros_like(input=even_num)
like_even_num

tensor([0, 0, 0, 0, 0])

Tensor data types

In [18]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device='cuda', # what device is your tensor on cuda or cpu
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.], device='cuda:0')

In [19]:
float_32_tensor.dtype

torch.float32

In [20]:
float_16_tesor = float_32_tensor.type(torch.float16)
float_16_tesor.dtype

torch.float16

In [21]:
# create tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.4513, 0.1531, 0.3900, 0.3897],
        [0.4841, 0.3460, 0.9479, 0.5352],
        [0.8878, 0.8887, 0.8672, 0.5378]])

In [22]:
# Find out details about some tensor
print(f'Datatype of tensor:     {some_tensor.dtype}')
print(f'Shape of tensor:        {some_tensor.shape}')
print(f'Device where tensor on: {some_tensor.shape}')

Datatype of tensor:     torch.float32
Shape of tensor:        torch.Size([3, 4])
Device where tensor on: torch.Size([3, 4])


Manipulating Tensors (tensor operations)

Tensor operation include:
* Addition
* Subtraction
* Multiplication
* Division
* Matrix Multiplication
  

In [23]:
tensor = torch.tensor([3,4,5])
tensor + 10

tensor([13, 14, 15])

In [24]:
tensor * 10

tensor([30, 40, 50])

In [25]:
tensor - 10

tensor([-7, -6, -5])

we have two ways for matrix multiplication:
* Element-wise
* two Matrix  (dot product)

In [27]:
# element-wise
print(tensor * tensor)

tensor([ 9, 16, 25])


In [29]:
# matrix multiplication
torch.matmul(tensor, tensor)

tensor(50)