In [1]:
import torch
torch.__version__

'2.4.0+cu121'

In [2]:
import torch
if torch.cuda.is_available():
    print("GPU is available")
else:
    print("GPU is not available")

GPU is available


#### Introduction to Tensors

In [44]:
scaler = torch.tensor(7)

In [46]:
# scaler
scaler.ndim
# get int from tensor
scaler.item()

7

In [47]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [50]:
vector.tolist()

[7, 7]

In [6]:
vector.size(), vector.ndim

(torch.Size([2]), 1)

In [51]:
# MATRIX
MATRIX = torch.tensor([[2,3], [4,5]])
MATRIX

tensor([[2, 3],
        [4, 5]])

In [54]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [55]:
TENSOR.ndim

3

#### Random Tensors

In [56]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0962, 0.1181, 0.6739, 0.9165],
        [0.0009, 0.1908, 0.1631, 0.1980],
        [0.0275, 0.8877, 0.4359, 0.7342]])

#### Zero and Ones

In [57]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [12]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [13]:
zeros.dtype

torch.float32

In [14]:
a=torch.zeros([2,4,4])

In [15]:
a[1]

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

#### Create a range of tensors and tensors like

In [16]:
# tensort.range()
even_num = torch.arange(start=0, end=10, step=2)
even_num

tensor([0, 2, 4, 6, 8])

In [17]:
# tensor.zeros_like()
like_even_num = torch.zeros_like(input=even_num)
like_even_num

tensor([0, 0, 0, 0, 0])

#### Tensor data types

In [59]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device='cuda', # what device is your tensor on cuda or cpu
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.], device='cuda:0')

In [19]:
float_32_tensor.dtype

torch.float32

In [60]:
float_16_tesor = float_32_tensor.type(torch.float16)
float_16_tesor.dtype

torch.float16

In [61]:
# create tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.7663, 0.4964, 0.6827, 0.4776],
        [0.8183, 0.9434, 0.3413, 0.9598],
        [0.6906, 0.6019, 0.5377, 0.5273]])

In [62]:
# Find out details about some tensor
print(f'Datatype of tensor:     {some_tensor.dtype}')
print(f'Shape of tensor:        {some_tensor.shape}')
print(f'Device where tensor on: {some_tensor.shape}')

Datatype of tensor:     torch.float32
Shape of tensor:        torch.Size([3, 4])
Device where tensor on: torch.Size([3, 4])


Manipulating Tensors (tensor operations)

Tensor operation include:
* Addition
* Subtraction
* Multiplication
* Division
* Matrix Multiplication
  

In [64]:
tensor = torch.tensor([3,4,5])
tensor + 10

tensor([13, 14, 15])

In [24]:
tensor * 10

tensor([30, 40, 50])

In [25]:
tensor - 10

tensor([-7, -6, -5])

we have two ways for matrix multiplication:
* Element-wise
* two Matrix  (dot product)

In [66]:
# element-wise
print(tensor * tensor)

tensor([ 9, 16, 25])


In [71]:
tensor.ndim

1

In [67]:
# matrix multiplication
torch.matmul(tensor, tensor)

tensor(50)

#### Max, Min and Mean

In [72]:
x = torch.arange(1,20)
x.max(), torch.max(x)

(tensor(19), tensor(19))

In [29]:
# input dtype should be either floating point or complex dtypes for calculating mean
x.type(torch.float32).mean()

tensor(10.)

#### Find the positional min and max

In [30]:
x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19])

In [31]:
x.argmin(), x.argmax()

(tensor(0), tensor(18))

#### Reshaping, stacking

In [32]:
import torch
x = torch.arange(0.,5.)
x, x.shape

(tensor([0., 1., 2., 3., 4.]), torch.Size([5]))

In [33]:
x.reshape(5,1)

tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.]])

In [34]:
# add extra dimension
x.reshape(1,5)

tensor([[0., 1., 2., 3., 4.]])

In [35]:
z = x.view(5,1)
z

tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.]])

In [36]:
# the view of a tensor shares the same memory as orginal so changing it effect 
z[0,0] = 5
z, x

(tensor([[5.],
         [1.],
         [2.],
         [3.],
         [4.]]),
 tensor([5., 1., 2., 3., 4.]))

#### squeezing and unsqueezing

In [84]:
# Returns a tensor with all specified dimensions of input of size 1 removed.
x_sample = torch.zeros(1,1,9)
x_squeezed = x_sample.squeeze()

x_sample.shape, x_squeezed.shape

(torch.Size([1, 1, 9]), torch.Size([9]))

In [85]:
# torch.unsqueeze() - adds a single dimension to a target tensort at specific dim
print(f"Previous target: \n{x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"Previous target: \n{x_unsqueezed}")
print(f"Previous shape: {x_unsqueezed.shape}")

Previous target: 
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0.])
Previous shape: torch.Size([9])
Previous target: 
tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0.]])
Previous shape: torch.Size([1, 9])


In [86]:
# torch permute change the dimensions order 
x_orginal = torch.randn(size=(224,224,3)) # 
x_permute = x_orginal.permute(2, 0, 1) # new order [color_channel, height, width]

print(f'Orginal shape: {x_orginal.shape}')
print(f'New shape    : {x_orginal.shape}')

Orginal shape: torch.Size([224, 224, 3])
New shape    : torch.Size([224, 224, 3])


#### Numpy In Pytorch

In [97]:
# numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # pytorch default datatype for numpy is float64
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [98]:
# tensor to numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [92]:
tensor

tensor([1., 1., 1., 1., 1., 1., 1.])

#### Reproducibility

In [102]:
import torch

random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

In [104]:
# reproducible random tensor
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C == random_tensor_D)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### GPU access with PyTorch

In [108]:
!nvidia-smi

Sat Aug 31 15:24:38 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.35.02              Driver Version: 560.94         CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1650        On  |   00000000:01:00.0 Off |                  N/A |
| N/A   48C    P8              2W /   50W |     142MiB /   4096MiB |      2%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [107]:
# check cuda is available
import torch
torch.cuda.is_available()

True

In [109]:
# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [111]:
# Count number of gpus
torch.cuda.device_count()

1

#### Putting Tesnors on the GPU

In [112]:
# create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [118]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

#### Moving Tensors Back to CPU

In [120]:
# If tensor is on GPU, can't transform it to numpy!
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [122]:
# To fix this issue first copy it on cpu
tensor_backTo_cpu = tensor.cpu().numpy()
tensor_backTo_cpu

array([1, 2, 3])